name: GlobalMissions
version: '${project.version}'
main: org.rankup.globalmissions.GlobalMissions
commands:
  missionreload:
    description: Reloads config
    aliases:
      - mr
      - missreload
  missionstart:
    description: Starts mission
    aliases:
      - ms
      - misstart
softdepend:
  - PlaceholderAPI
depend:
  - Vault